default:
  title: 'iReport'
  css: ['bootstrap.min.css', 'bootstrap-responsive.min.css', 'custom-style.css']
  js: ['jquery-1.9.1.min.js', 'bootstrap.min.js', 'custom-script.js']

inicio/login:
  title: 'Acesso ao sistema'